In [1]:
import pandas as pd 
import numpy as np

In [2]:
crop_p = pd.read_csv("Crop and fertilizer dataset.csv")
crop_p

District_Name Soil_color  Nitrogen  Phosphorus  Potassium   pH  Rainfall  \
0         Kolhapur      Black        75          50        100  6.5      1000   
1         Kolhapur      Black        80          50        100  6.5      1000   
2         Kolhapur      Black        85          50        100  6.5      1000   
3         Kolhapur      Black        90          50        100  6.5      1000   
4         Kolhapur      Black        95          50        100  6.5      1000   
...            ...        ...       ...         ...        ...  ...       ...   
4508          Pune      Black       130          80        150  7.0      1400   
4509          Pune      Black       135          80        150  7.0      1400   
4510          Pune      Black       140          80        150  7.0      1400   
4511          Pune      Black       145          80        150  7.0      1400   
4512          Pune      Black       150          80        150  7.0      1400   

      Temperature       Crop Fertilizer                          Link  
0              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo  
1              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo  
2              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo  
3              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo  
4              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo  
...           ...        ...        ...                           ...  
4508           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo  
4509           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo  
4510           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo  
4511           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo  
4512           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo  

[4513 rows x 11 columns]

#Encoding 

In [3]:
crop_p["Crop"].value_counts()

Crop
Sugarcane    1010
Wheat         859
Cotton        650
Jowar         394
Maize         350
Rice          309
Groundnut     177
Tur           126
Ginger        125
Grapes        125
Urad           99
Moong          99
Gram           78
Turmeric       55
Soybean        45
Masoor         12
Name: count, dtype: int64

In [4]:
crop_dict={
    "Sugarcane":1,
    "Wheat":2,
    "Cotton":3,
    "Jowar":4,
    "Maize":5,
    "Rice":6,
    "Groundnut":7,
    "Tur":8,
    "Ginger":9,
    "Grapes":10,
    "Urad":11,
    "Moong":12,
    "Gram":13,
    "Turmeric":14,
    "Soybean":15,
    "Masoor":16,
}
crop_p['crop_num']=crop_p["Crop"].map(crop_dict)

In [5]:
crop_p['crop_num'].value_counts()

crop_num
1     1010
2      859
3      650
4      394
5      350
6      309
7      177
8      126
9      125
10     125
11      99
12      99
13      78
14      55
15      45
16      12
Name: count, dtype: int64

In [6]:
crop_p

District_Name Soil_color  Nitrogen  Phosphorus  Potassium   pH  Rainfall  \
0         Kolhapur      Black        75          50        100  6.5      1000   
1         Kolhapur      Black        80          50        100  6.5      1000   
2         Kolhapur      Black        85          50        100  6.5      1000   
3         Kolhapur      Black        90          50        100  6.5      1000   
4         Kolhapur      Black        95          50        100  6.5      1000   
...            ...        ...       ...         ...        ...  ...       ...   
4508          Pune      Black       130          80        150  7.0      1400   
4509          Pune      Black       135          80        150  7.0      1400   
4510          Pune      Black       140          80        150  7.0      1400   
4511          Pune      Black       145          80        150  7.0      1400   
4512          Pune      Black       150          80        150  7.0      1400   

      Temperature       Crop Fertilizer                          Link  \
0              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo   
1              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo   
2              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo   
3              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo   
4              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo   
...           ...        ...        ...                           ...   
4508           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo   
4509           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo   
4510           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo   
4511           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo   
4512           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo   

      crop_num  
0            1  
1            1  
2            1  
3            1  
4            1  
...        ...  
4508         1  
4509         1  
4510         1  
4511         1  
4512         1  

[4513 rows x 12 columns]

In [7]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

# Assuming df is your dataframe with the project columns
# Encoding categorical variables
df_encoded = pd.get_dummies(crop_p, columns=['Soil_color', 'District_Name'])
print(df_encoded)
print(df_encoded.columns)
# Handling missing values
imputer = SimpleImputer(strategy='mean')
df_encoded[['Nitrogen', 'Phosphorus', 'Potassium', 'pH', 'Rainfall', 'Temperature']] = imputer.fit_transform(df_encoded[['Nitrogen', 'Phosphorus', 'Potassium', 'pH', 'Rainfall', 'Temperature']])

# Standardization
scaler = StandardScaler()
df_encoded[['Nitrogen', 'Phosphorus', 'Potassium', 'pH', 'Rainfall', 'Temperature']] = scaler.fit_transform(df_encoded[['Nitrogen', 'Phosphorus', 'Potassium', 'pH', 'Rainfall', 'Temperature']])
df_encoded

      Nitrogen  Phosphorus  Potassium   pH  Rainfall  Temperature       Crop  \
0           75          50        100  6.5      1000           20  Sugarcane   
1           80          50        100  6.5      1000           20  Sugarcane   
2           85          50        100  6.5      1000           20  Sugarcane   
3           90          50        100  6.5      1000           20  Sugarcane   
4           95          50        100  6.5      1000           20  Sugarcane   
...        ...         ...        ...  ...       ...          ...        ...   
4508       130          80        150  7.0      1400           30  Sugarcane   
4509       135          80        150  7.0      1400           30  Sugarcane   
4510       140          80        150  7.0      1400           30  Sugarcane   
4511       145          80        150  7.0      1400           30  Sugarcane   
4512       150          80        150  7.0      1400           30  Sugarcane   

     Fertilizer                        

Nitrogen  Phosphorus  Potassium        pH  Rainfall  Temperature  \
0    -0.536307   -0.262348   1.020087 -0.344356  0.718351    -1.003130   
1    -0.404923   -0.262348   1.020087 -0.344356  0.718351    -1.003130   
2    -0.273539   -0.262348   1.020087 -0.344356  0.718351    -1.003130   
3    -0.142155   -0.262348   1.020087 -0.344356  0.718351    -1.003130   
4    -0.010772   -0.262348   1.020087 -0.344356  0.718351    -1.003130   
...        ...         ...        ...       ...       ...          ...   
4508  0.908915    1.550324   2.421120  0.455479  2.307526     0.692741   
4509  1.040299    1.550324   2.421120  0.455479  2.307526     0.692741   
4510  1.171683    1.550324   2.421120  0.455479  2.307526     0.692741   
4511  1.303067    1.550324   2.421120  0.455479  2.307526     0.692741   
4512  1.434451    1.550324   2.421120  0.455479  2.307526     0.692741   

           Crop Fertilizer                          Link  crop_num  ...  \
0     Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo         1  ...   
1     Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo         1  ...   
2     Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo         1  ...   
3     Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo         1  ...   
4     Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo         1  ...   
...         ...        ...                           ...       ...  ...   
4508  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo         1  ...   
4509  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo         1  ...   
4510  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo         1  ...   
4511  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo         1  ...   
4512  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo         1  ...   

      Soil_color_Light Brown  Soil_color_Medium Brown  Soil_color_Red  \
0                      False                    False           False   
1                      False                    False           False   
2                      False                    False           False   
3                      False                    False           False   
4                      False                    False           False   
...                      ...                      ...             ...   
4508                   False                    False           False   
4509                   False                    False           False   
4510                   False                    False           False   
4511                   False                    False           False   
4512                   False                    False           False   

      Soil_color_Red   Soil_color_Reddish Brown  District_Name_Kolhapur  \
0               False                     False                    True   
1               False                     False                    True   
2               False                     False                    True   
3               False                     False                    True   
4               False                     False                    True   
...               ...                       ...                     ...   
4508            False                     False                   False   
4509            False                     False                   False   
4510            False                     False                   False   
4511            False                     False                   False   
4512            False                     False                   False   

      District_Name_Pune  District_Name_Sangli  District_Name_Satara  \
0                  False                 False                 False   
1                  False                 False                 False   
2                  False                 False                 False   
3                  False                 False                 False   
4                  False                 False                 False   
...   

In [8]:
X= df_encoded.drop(["crop_num","Fertilizer","Link","Crop"],axis=1)
y = crop_p['crop_num']

In [9]:
from sklearn.model_selection import train_test_split


In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [11]:
X_train

Nitrogen  Phosphorus  Potassium        pH  Rainfall  Temperature  \
3903 -1.850145   -1.772908  -0.380946 -1.144191  3.102113    -0.155195   
999  -0.273539    0.039764  -0.661152 -0.344356 -0.076237    -1.851066   
2366 -0.273539   -0.262348  -0.521049  0.455479  2.307526     0.692741   
1474  0.646148    1.248212   0.459674  2.854984 -1.268118    -0.155195   
3859 -0.667691    0.341876  -0.521049 -1.144191 -0.076237    -0.155195   
...        ...         ...        ...       ...       ...          ...   
4426  1.171683    0.946100   1.720604  0.455479  2.307526     0.692741   
466   0.514764    0.341876   0.319571  1.255314  0.718351     1.540676   
3092 -0.930458   -0.564460  -0.100739 -1.144191 -0.870824    -1.003130   
3772 -0.930458   -0.262348  -0.240842  1.255314  0.321057     0.692741   
860   0.383380    0.341876  -0.521049  0.455479 -0.473530    -0.155195   

      Soil_color_Black  Soil_color_Dark Brown  Soil_color_Light Brown  \
3903              True                  False                   False   
999              False                   True                   False   
2366             False                  False                   False   
1474              True                  False                   False   
3859             False                  False                   False   
...                ...                    ...                     ...   
4426              True                  False                   False   
466              False                  False                   False   
3092              True                  False                   False   
3772             False                  False                   False   
860              False                   True                   False   

      Soil_color_Medium Brown  Soil_color_Red  Soil_color_Red   \
3903                    False           False            False   
999                     False           False            False   
2366                    False            True            False   
1474                    False           False            False   
3859                    False            True            False   
...                       ...             ...              ...   
4426                    False           False            False   
466                     False           False             True   
3092                    False           False            False   
3772                    False            True            False   
860                     False           False            False   

      Soil_color_Reddish Brown  District_Name_Kolhapur  District_Name_Pune  \
3903                     False                   False               False   
999                      False                    True               False   
2366                     False                   False               False   
1474                     False                   False               False   
3859                     False                   False               False   
...                        ...                     ...                 ...   
4426                     False                   False                True   
466                      False                    True               False   
3092                     False                   False               False   
3772                     False                   False               False   
860                      False                    True               False   

      District_Name_Sangli  District_Name_Satara  District_Name_Solapur  
3903                  True                 False                  False  
999                  False                 False                  False  
2366                 False                  True                  False  
1474                 False                 False                   True  
3859                  True                 False                  False  
...                    ...                   ...                  

In [12]:
y_train

3903    14
999      2
2366     6
1474     3
3859     4
        ..
4426     1
466      3
3092     2
3772     4
860      2
Name: crop_num, Length: 3610, dtype: int64

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix




# Initialize the logistic regression model
logreg_model = LogisticRegression()

# Train the model on the training set
logreg_model.fit(X_train, y_train)

# Predictions on the test set
y_pred = logreg_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print the evaluation metrics
print(f'Accuracy: {accuracy:.2f}')
print('\nConfusion Matrix:')
print(conf_matrix)
print('\nClassification Report:')
print(classification_rep)


Accuracy: 0.96

Confusion Matrix:
[[205   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 175   0   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1 140   3   0   0   0   0   0   0   0   2   0   0   0   0]
 [  0   0   0  65   0   0   1   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0  71   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  64   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   8   0   0  31   2   0   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0  20   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0  26   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  19   0   0   0   0   0   0]
 [  0   0   0   3   0   0   2   2   0   0   7   1   1   0   2   0]
 [  0   0   0   0   0   0   0   0   0   0   0  13   0   0   0   0]
 [  0   0   0   0   0   0   3   0   0   0   0   0  11   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0   0   0   0  11   0   0]
 [  0   0   0   0   0   0   

/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [25]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
# Initialize the decision tree classifier
clf = DecisionTreeClassifier(random_state=42)

# Fit the model to the training data
clf_model=clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf_model.predict(X_test)




# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Decision Tree Accuracy:{accuracy}")

Decision Tree Accuracy:0.9966777408637874


In [26]:
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import metrics
import matplotlib.pyplot as plt

In [35]:
# Plot the decision tree
plt.figure(figsize=(15, 10))
plot_tree(clf_model, filled=True, feature_names=list(df_encoded.columns), class_names=list(crop_p["Crop"].unique()),rounded=True)
plt.show()